/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiInterviewRouteImport } from './routes/api/interview'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated.upgrade'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated.tracker'
import { Route as AuthenticatedSmartApplyRouteImport } from './routes/_authenticated.smart-apply'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated.roadmap'
import { Route as AuthenticatedJobMatchRouteImport } from './routes/_authenticated.job-match'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated.interview'
import { Route as AuthenticatedDeleteAccountRouteImport } from './routes/_authenticated.delete-account'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCvBuilderRouteImport } from './routes/_authenticated.cv-builder'
import { Route as AuthenticatedCoverLetterRouteImport } from './routes/_authenticated.cover-letter'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as ApiPublicPaymentsRouteImport } from './routes/api/public/payments'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterviewRoute = ApiInterviewRouteImport.update({
  id: '/api/interview',
  path: '/api/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSmartApplyRoute = AuthenticatedSmartApplyRouteImport.update({
  id: '/smart-apply',
  path: '/smart-apply',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobMatchRoute = AuthenticatedJobMatchRouteImport.update({
  id: '/job-match',
  path: '/job-match',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeleteAccountRoute =
  AuthenticatedDeleteAccountRouteImport.update({
    id: '/delete-account',
    path: '/delete-account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCvBuilderRoute = AuthenticatedCvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoverLetterRoute =
  AuthenticatedCoverLetterRouteImport.update({
    id: '/cover-letter',
    path: '/cover-letter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsRoute = ApiPublicPaymentsRouteImport.update({
  id: '/api/public/payments',
  path: '/api/public/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delete-account': typeof AuthenticatedDeleteAccountRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/job-match': typeof AuthenticatedJobMatchRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/smart-apply': typeof AuthenticatedSmartApplyRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/payments': typeof ApiPublicPaymentsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/delete-account': typeof AuthenticatedDeleteAccountRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/job-match': typeof AuthenticatedJobMatchRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/smart-apply': typeof AuthenticatedSmartApplyRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/payments': typeof ApiPublicPaymentsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/cover-letter': typeof AuthenticatedCoverLetterRoute
  '/_authenticated/cv-builder': typeof AuthenticatedCvBuilderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/delete-account': typeof AuthenticatedDeleteAccountRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/job-match': typeof AuthenticatedJobMatchRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/smart-apply': typeof AuthenticatedSmartApplyRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/api/interview': typeof ApiInterviewRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/public/payments': typeof ApiPublicPaymentsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/terms'
    | '/billing'
    | '/cover-letter'
    | '/cv-builder'
    | '/dashboard'
    | '/delete-account'
    | '/interview'
    | '/job-match'
    | '/roadmap'
    | '/smart-apply'
    | '/tracker'
    | '/upgrade'
    | '/api/interview'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/public/payments'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/terms'
    | '/billing'
    | '/cover-letter'
    | '/cv-builder'
    | '/dashboard'
    | '/delete-account'
    | '/interview'
    | '/job-match'
    | '/roadmap'
    | '/smart-apply'
    | '/tracker'
    | '/upgrade'
    | '/api/interview'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/public/payments'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/support'
    | '/terms'
    | '/_authenticated/billing'
    | '/_authenticated/cover-letter'
    | '/_authenticated/cv-builder'
    | '/_authenticated/dashboard'
    | '/_authenticated/delete-account'
    | '/_authenticated/interview'
    | '/_authenticated/job-match'
    | '/_authenticated/roadmap'
    | '/_authenticated/smart-apply'
    | '/_authenticated/tracker'
    | '/_authenticated/upgrade'
    | '/api/interview'
    | '/api/transcribe'
    | '/api/tts'
    | '/api/public/payments'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiInterviewRoute: typeof ApiInterviewRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicPaymentsRoute: typeof ApiPublicPaymentsRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interview': {
      id: '/api/interview'
      path: '/api/interview'
      fullPath: '/api/interview'
      preLoaderRoute: typeof ApiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/smart-apply': {
      id: '/_authenticated/smart-apply'
      path: '/smart-apply'
      fullPath: '/smart-apply'
      preLoaderRoute: typeof AuthenticatedSmartApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/job-match': {
      id: '/_authenticated/job-match'
      path: '/job-match'
      fullPath: '/job-match'
      preLoaderRoute: typeof AuthenticatedJobMatchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/delete-account': {
      id: '/_authenticated/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof AuthenticatedDeleteAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cv-builder': {
      id: '/_authenticated/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof AuthenticatedCvBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cover-letter': {
      id: '/_authenticated/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof AuthenticatedCoverLetterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments': {
      id: '/api/public/payments'
      path: '/api/public/payments'
      fullPath: '/api/public/payments'
      preLoaderRoute: typeof ApiPublicPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCoverLetterRoute: typeof AuthenticatedCoverLetterRoute
  AuthenticatedCvBuilderRoute: typeof AuthenticatedCvBuilderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeleteAccountRoute: typeof AuthenticatedDeleteAccountRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedJobMatchRoute: typeof AuthenticatedJobMatchRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSmartApplyRoute: typeof AuthenticatedSmartApplyRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCoverLetterRoute: AuthenticatedCoverLetterRoute,
  AuthenticatedCvBuilderRoute: AuthenticatedCvBuilderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeleteAccountRoute: AuthenticatedDeleteAccountRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedJobMatchRoute: AuthenticatedJobMatchRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSmartApplyRoute: AuthenticatedSmartApplyRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiInterviewRoute: ApiInterviewRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicPaymentsRoute: ApiPublicPaymentsRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
